
SERVER_IP = "15.207.230.199"
AGENT_KEY = "4UjPPhRMTAXvR85CnpV3JdB6"

API_BASE_URL = f"http://{SERVER_IP}/api"
WEBSOCKET_URL = f"ws://{SERVER_IP}:8080/app/gamezonekey"

HEARTBEAT_INTERVAL = 30
LOG_FILE = "logs/agent.log"